export const ADMIN = "ADMIN";
export const BOOK_GENRE = ["COMEDY","THRILLER","SCIENCE","MYSTERY","FICTION","NON_FICTION"]
export const MEMBERSHIP_STATUS = ['ACTIVE','INACTIVE','DEFAULTER']
export const ISSUE_TRANSACTION_TYPE = ["PENDING","ISSUED","RETURNED"]
